### ISSUE TITLE
Training Model Attempt

### ISSUE THREAD

**Issue by skshadan** [nuengdioew/Coqui-Sonic-Characters-TTS#1]
Hello, guide me how can i train it locally, on my system???

**Comment by skshadan** [comment]
also, how can i use your trained model?????

**Comment by silvervens** [comment]
Oof, this has been a long time. To use my pre-trained model. 

> also, how can i use your trained model?????

To run you can download TTS via python and setup a basic script.
https://youtu.be/MYRgWwis1Jk

The YT channels that host local trainings can also be found by searching up Google. Or literally using Jupyter and requirements. fulfilled.

**Comment by skshadan** [comment]
everything is working fine, what i want is a good model ( any pre trained model ) or how can i train my own model easily locally?

**Comment by skshadan** [comment]
Do you have any pre-trained models available?

**Comment by silvervens** [comment]
> Do you have any pre-trained models available?

Only Silver unfortunately, spent all of my google colab monthly subscription on it. No more powers left. If you wished to submit other characters feel free to do so :D

**Comment by skshadan** [comment]
also i am getting this error when i continue my training?

Traceback (most recent call last):
  File "E:\KL2.0\CODEZ\Coqui\tts-coqui\TTS\venv\lib\site-packages\trainer\trainer.py", line 1591, in fit
    self._fit()
  File "E:\KL2.0\CODEZ\Coqui\tts-coqui\TTS\venv\lib\site-packages\trainer\trainer.py", line 1548, in _fit
    self.test_run()
  File "E:\KL2.0\CODEZ\Coqui\tts-coqui\TTS\venv\lib\site-packages\trainer\trainer.py", line 1466, in test_run
    test_outputs = self.model.test_run(self.training_assets)
  File "E:\KL2.0\CODEZ\Coqui\tts-coqui\TTS\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\KL2.0\CODEZ\Coqui\tts-coqui\TTS\venv\lib\site-packages\TTS\tts\models\vits.py", line 1442, in test_run
    wav, alignment, _, _ = synthesis(
  File "E:\KL2.0\CODEZ\Coqui\tts-coqui\TTS\venv\lib\site-packages\TTS\tts\utils\synthesis.py", line 186, in synthesis
    model.tokenizer.text_to_ids(text, language=language_name),
  File "E:\KL2.0\CODEZ\Coqui\tts-coqui\TTS\venv\lib\site-packages\TTS\tts\utils\text\tokenizer.py", line 108, in text_to_ids
    text = self.text_cleaner(text)
  File "E:\KL2.0\CODEZ\Coqui\tts-coqui\TTS\venv\lib\site-packages\TTS\tts\utils\text\cleaners.py", line 125, in phoneme_cleaners
    text = en_normalize_numbers(text)
  File "E:\KL2.0\CODEZ\Coqui\tts-coqui\TTS\venv\lib\site-packages\TTS\tts\utils\text\english\number_norm.py", line 92, in normalize_numbers
    text = re.sub(_comma_number_re, _remove_commas, text)
  File "C:\Users\shada\AppData\Local\Programs\Python\Python38\lib\re.py", line 208, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object

**Comment by nuengdioew** [comment]
I have no idea on how to fix that… Perhaps look closer to the requirements. Sent from Mail for Windows From: ShadanSent: Friday, August 18, 2023 11:59 PMTo: nuengdioew/Coqui-TTS-Models-Sonic-CharactersCc: WOW_MEME; CommentSubject: Re: [nuengdioew/Coqui-TTS-Models-Sonic-Characters] help! (Issue #1) also i am getting this error when i continue my training?Traceback (most recent call last):File "E:\KL2.0\CODEZ\Coqui\tts-coqui\TTS\venv\lib\site-packages\trainer\trainer.py", line 1591, in fitself._fit()File "E:\KL2.0\CODEZ\Coqui\tts-coqui\TTS\venv\lib\site-packages\trainer\trainer.py", line 1548, in _fitself.test_run()File "E:\KL2.0\CODEZ\Coqui\tts-coqui\TTS\venv\lib\site-packages\trainer\trainer.py", line 1466, in test_runtest_outputs = self.model.test_run(self.training_assets)File "E:\KL2.0\CODEZ\Coqui\tts-coqui\TTS\venv\lib\site-packages\torch\utils_contextlib.py", line 115, in decorate_contextreturn func(*args, **kwargs)File "E:\KL2.0\CODEZ\Coqui\tts-coqui\TTS\venv\lib\site-packages\TTS\tts\models\vits.py", line 1442, in test_runwav, alignment, _, _ = synthesis(File "E:\KL2.0\CODEZ\Coqui\tts-coqui\TTS\venv\lib\site-packages\TTS\tts\utils\synthesis.py", line 186, in synthesismodel.tokenizer.text_to_ids(text, language=language_name),File "E:\KL2.0\CODEZ\Coqui\tts-coqui\TTS\venv\lib\site-packages\TTS\tts\utils\text\tokenizer.py", line 108, in text_to_idstext = self.text_cleaner(text)File "E:\KL2.0\CODEZ\Coqui\tts-coqui\TTS\venv\lib\site-packages\TTS\tts\utils\text\cleaners.py", line 125, in phoneme_cleanerstext = en_normalize_numbers(text)File "E:\KL2.0\CODEZ\Coqui\tts-coqui\TTS\venv\lib\site-packages\TTS\tts\utils\text\english\number_norm.py", line 92, in normalize_numberstext = re.sub(_comma_number_re, _remove_commas, text)File "C:\Users\shada\AppData\Local\Programs\Python\Python38\lib\re.py", line 208, in subreturn _compile(pattern, flags).sub(repl, string, count)TypeError: expected string or bytes-like object—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by silvervens** [comment]
> also i am getting this error when i continue my training?
> 
> Traceback (most recent call last): File "E:\KL2.0\CODEZ\Coqui\tts-coqui\TTS\venv\lib\site-packages\trainer\trainer.py", line 1591, in fit self._fit() File "E:\KL2.0\CODEZ\Coqui\tts-coqui\TTS\venv\lib\site-packages\trainer\trainer.py", line 1548, in _fit self.test_run() File "E:\KL2.0\CODEZ\Coqui\tts-coqui\TTS\venv\lib\site-packages\trainer\trainer.py", line 1466, in test_run test_outputs = self.model.test_run(self.training_assets) File "E:\KL2.0\CODEZ\Coqui\tts-coqui\TTS\venv\lib\site-packages\torch\utils_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "E:\KL2.0\CODEZ\Coqui\tts-coqui\TTS\venv\lib\site-packages\TTS\tts\models\vits.py", line 1442, in test_run wav, alignment, _, _ = synthesis( File "E:\KL2.0\CODEZ\Coqui\tts-coqui\TTS\venv\lib\site-packages\TTS\tts\utils\synthesis.py", line 186, in synthesis model.tokenizer.text_to_ids(text, language=language_name), File "E:\KL2.0\CODEZ\Coqui\tts-coqui\TTS\venv\lib\site-packages\TTS\tts\utils\text\tokenizer.py", line 108, in text_to_ids text = self.text_cleaner(text) File "E:\KL2.0\CODEZ\Coqui\tts-coqui\TTS\venv\lib\site-packages\TTS\tts\utils\text\cleaners.py", line 125, in phoneme_cleaners text = en_normalize_numbers(text) File "E:\KL2.0\CODEZ\Coqui\tts-coqui\TTS\venv\lib\site-packages\TTS\tts\utils\text\english\number_norm.py", line 92, in normalize_numbers text = re.sub(_comma_number_re, _remove_commas, text) File "C:\Users\shada\AppData\Local\Programs\Python\Python38\lib\re.py", line 208, in sub return _compile(pattern, flags).sub(repl, string, count) TypeError: expected string or bytes-like object

I have no idea, perhaps check requirements?

**Comment by skshadan** [comment]
yeah! i tried! btw loved your model! it's soo good mann!! but too much noisy!

**Comment by silvervens** [comment]
> yeah! i tried! btw loved your model! it's soo good mann!! but too much noisy!

Is it that you need the audios and things to set it up??? Like the CIVS and the Audio samples?

**Comment by skshadan** [comment]
Yess! can u pls guide me on-
how to make high quality dataset?
how to train properly?
how much data is required to get a good voice?
how to finetune a model?

**Comment by silvervens** [comment]
> Yess! can u pls guide me on- how to make high quality dataset? how to train properly? how much data is required to get a good voice? how to finetune a model?

I literally poured in tons of Audio samples and used the subtitle tool to make a subtitle out of it and then did more. It's a painful process. All it was from a tutorial, I don't remember much, but seemingly I kinda gave up since my voice is actually Silver-like. So... 

Don't think I have that in my google drive, I use the google colab and inserted it via directories ending up with a finished fine-tuned model... Wait... Lemme see... 

Go to google colab and skip to the fine tune and continue from there. 
![image](https://github.com/nuengdioew/Coqui-TTS-Models-Sonic-Characters/assets/22748717/2092fceb-8fe8-4ae9-8ec9-fd2b3d0d8300)

**Comment by silvervens** [comment]
That way you can continue training my Silver's voice model :D

Don't forget to send it here, I will mark this as a contribution and will replace the model with yours trained, since my google colab subscription is cancelled.

**Comment by skshadan** [comment]
can u please the google collab link?

**Comment by skshadan** [comment]
Thanks for replying. I am from India, so first, Namaste!
I am using Coqui to create an AI NPC for my game. For that, I am searching for a well-trained model that supports Hindi as well. I don't know what the process is. So, basically, if you have trained a good model, could you please explain the whole process of how it works? or share your model? Also, related to expressions, how can I get good expressions as you mentioned in the coqui issue.
Thanks.

**Comment by skshadan** [comment]
this is my discord : shadaen#8965
if you just add me there, so that we can talk properly, if you don't any problem!

Thanks!

**Comment by silvervens** [comment]
> 

The link is with the page... It's there, just scroll DOOOWN!

Scrolly If I'm late :(

**Comment by skshadan** [comment]
Yeah! got it man! Thanks! by the way do you have any other good models available for coqui??? also do u know about finetuning?? how can i finetune the model??? also one more question - your model have some noise when it is generating the audio.

**Comment by silvervens** [comment]
> Yeah! got it man! Thanks! by the way do you have any other good models available for coqui??? also do u know about finetuning?? how can i finetune the model??? also one more question - your model have some noise when it is generating the audio.

I don't know much on how to fine tune things. Although, when fine tuning I leave it on google colab doing its thing. Apparently, it keeps on getting better the more iterations it had. 

I have no idea what the noise is, but I think... Hmm... Prolly' something that has to do with tensor flow thingy...

I got no other models unless someone decided to train/make a model from Coqui that is for example Shadow, Sonic and more.
I will be accepting Sonic characters sent from the "issues" to be added here.

**Comment by skshadan** [comment]
sure! i will try to train sonic model :)))
also much data needed??

**Comment by silvervens** [comment]
> sure! i will try to train sonic model :))) also much data needed??

https://drive.google.com/drive/folders/1B2ZiSnMjNdcQiP8i2DkX7fCo_q6fy8jB?usp=sharing

Here's the training data of Silver the hedgehog... It's a lot...

**Comment by skshadan** [comment]
hey, when i am training getting this error -
Traceback (most recent call last):
  File "train_vits.py", line 96, in <module>
    main()
  File "train_vits.py", line 88, in main
    trainer.fit()
  File "E:\KL2.0\CODEZ\Coqui\tts-coqui\TTS\venv\lib\site-packages\trainer\trainer.py", line 1610, in fit
    remove_experiment_folder(self.output_path)
  File "E:\KL2.0\CODEZ\Coqui\tts-coqui\TTS\venv\lib\site-packages\trainer\generic_utils.py", line 64, in remove_experiment_folder
    fs.rm(experiment_path, recursive=True)
  File "E:\KL2.0\CODEZ\Coqui\tts-coqui\TTS\venv\lib\site-packages\fsspec\implementations\local.py", line 172, in rm
    shutil.rmtree(p)
  File "C:\Users\shada\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 730, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\shada\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 608, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\shada\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 606, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'E:/KL2.0/CODEZ/Coqui/tts-coqui/TTS/recipes/ljspeech/vits_tts/bheem-voice-August-24-2023_11+27AM-409db505\\events.out.tfevents.1692856674.Shadaen'

**Comment by silvervens** [comment]
> 

I personally have no Idea... I use google colab! Did you use jupyter notebook?

Check all the important libraries.

**Comment by skshadan** [comment]
Hello, thanks for the help. I want to know what the process is for creating a dataset to analyze emotions in speech. Is the dataset created based on emotions, or is there a process for capturing emotions in speech?

**Comment by skshadan** [comment]
???

**Comment by skshadan** [comment]
can you please tell, how much time it took for you to train the model??

**Comment by silvervens** [comment]
> 
Only audio clips unfortunately... You can go to the link and see how much data I've put... No emotions unfortunately, due to how limiting audio resources are...

**Comment by silvervens** [comment]
> > sure! i will try to train sonic model :))) also much data needed??
> 
> https://drive.google.com/drive/folders/1B2ZiSnMjNdcQiP8i2DkX7fCo_q6fy8jB?usp=sharing
> 
> Here's the training data of Silver the hedgehog... It's a lot...

this!

**Comment by skshadan** [comment]
hey bro- try this and tell me!!

https://huggingface.co/sk0032/coqui-tts-model

**Comment by silvervens** [comment]
> hey bro- try this and tell me!!
> 
> https://huggingface.co/sk0032/coqui-tts-model

I will test it tomorrow, I likely got some parts wrong on the installations. Is this silver's model?

**Comment by silvervens** [comment]
> hey bro- try this and tell me!!
> 
> https://huggingface.co/sk0032/coqui-tts-model
[voice.zip](https://github.com/silvervens/Coqui-TTS-Models-Sonic-Characters/files/12561053/voice.zip)

Is it my model that you trained or silver's????

Tested now ended up with these results:

**Comment by silvervens** [comment]
[voice.zip](https://github.com/silvervens/Coqui-TTS-Models-Sonic-Characters/files/12561059/voice.zip)

**Comment by skshadan** [comment]
yoo!! hey man, can i get ur mail or discord?

**Comment by silvervens** [comment]
Sure! Discord as “silvervens” LITERALLY!!! Sent from Mail for Windows From: ShadanSent: Friday, September 29, 2023 6:18 PMTo: silvervens/Coqui-TTS-Models-Sonic-CharactersCc: SilverVens; CommentSubject: Re: [silvervens/Coqui-TTS-Models-Sonic-Characters] Training Model Attempt (Issue #1) yoo!! hey man, can i get ur mail or discord?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
